<?php
$this->eu_countries = array(
    "BE",
    "BG",
    "CY",
    "DK",
    "DE",
    "EE",
    "FI",
    "FR",
    "GR",
    "HU",
    "IE",
    "IT",
    "HR",
    "LV",
    "LT",
    "LU",
    "MT",
    "NL",
    "AT",
    "PL",
    "PT",
    "RO",
    "SK",
    "SI",
    "ES",
    "CZ",
    "GB",
    "VL",
    "SE"
);

$this->regions = array(
    'us' => array(
        'label' => __('US', 'complianz'),
        'countries' => array('us'),
        'law' => __("CaCPA", 'complianz'),
    ),

    'eu' => array(
        'label' => __('EU', 'complianz'),
        'countries' => $this->eu_countries,
        'law' => __("GDPR", 'complianz'),
    )
);



$this->cookie_consent_converter = array(
    "GB" => "UK",
);

$this->countries = array
(
    'AF' => __('Afghanistan', 'complianz'),
    'AX' => __('Aland Islands', 'complianz'),
    'AL' => __('Albania', 'complianz'),
    'DZ' => __('Algeria', 'complianz'),
    'AS' => __('American Samoa', 'complianz'),
    'AD' => __('Andorra', 'complianz'),
    'AO' => __('Angola', 'complianz'),
    'AI' => __('Anguilla', 'complianz'),
    'AQ' => __('Antarctica', 'complianz'),
    'AG' => __('Antigua And Barbuda', 'complianz'),
    'AR' => __('Argentina', 'complianz'),
    'AM' => __('Armenia', 'complianz'),
    'AW' => __('Aruba', 'complianz'),
    'AU' => __('Australia', 'complianz'),
    'AT' => __('Austria', 'complianz'),
    'AZ' => __('Azerbaijan', 'complianz'),
    'BS' => __('Bahamas', 'complianz'),
    'BH' => __('Bahrain', 'complianz'),
    'BD' => __('Bangladesh', 'complianz'),
    'BB' => __('Barbados', 'complianz'),
    'BY' => __('Belarus', 'complianz'),
    'BE' => __('Belgium', 'complianz'),
    'BZ' => __('Belize', 'complianz'),
    'BJ' => __('Benin', 'complianz'),
    'BM' => __('Bermuda', 'complianz'),
    'BT' => __('Bhutan', 'complianz'),
    'BO' => __('Bolivia', 'complianz'),
    'BA' => __('Bosnia And Herzegovina', 'complianz'),
    'BW' => __('Botswana', 'complianz'),
    'BV' => __('Bouvet Island', 'complianz'),
    'BR' => __('Brazil', 'complianz'),
    'IO' => __('British Indian Ocean Territory', 'complianz'),
    'BN' => __('Brunei Darussalam', 'complianz'),
    'BG' => __('Bulgaria', 'complianz'),
    'BF' => __('Burkina Faso', 'complianz'),
    'BI' => __('Burundi', 'complianz'),
    'KH' => __('Cambodia', 'complianz'),
    'CM' => __('Cameroon', 'complianz'),
    'CA' => __('Canada', 'complianz'),
    'CV' => __('Cape Verde', 'complianz'),
    'KY' => __('Cayman Islands', 'complianz'),
    'CF' => __('Central African Republic', 'complianz'),
    'TD' => __('Chad', 'complianz'),
    'CL' => __('Chile', 'complianz'),
    'CN' => __('China', 'complianz'),
    'CX' => __('Christmas Island', 'complianz'),
    'CC' => __('Cocos (Keeling) Islands', 'complianz'),
    'CO' => __('Colombia', 'complianz'),
    'KM' => __('Comoros', 'complianz'),
    'CG' => __('Congo', 'complianz'),
    'CD' => __('Congo, Democratic Republic', 'complianz'),
    'CK' => __('Cook Islands', 'complianz'),
    'CR' => __('Costa Rica', 'complianz'),
    'CI' => __('Cote D\'Ivoire', 'complianz'),
    'HR' => __('Croatia', 'complianz'),
    'CU' => __('Cuba', 'complianz'),
    'CY' => __('Cyprus', 'complianz'),
    'CZ' => __('Czech Republic', 'complianz'),
    'DK' => __('Denmark', 'complianz'),
    'DJ' => __('Djibouti', 'complianz'),
    'DM' => __('Dominica', 'complianz'),
    'DO' => __('Dominican Republic', 'complianz'),
    'EC' => __('Ecuador', 'complianz'),
    'EG' => __('Egypt', 'complianz'),
    'SV' => __('El Salvador', 'complianz'),
    'GQ' => __('Equatorial Guinea', 'complianz'),
    'ER' => __('Eritrea', 'complianz'),
    'EE' => __('Estonia', 'complianz'),
    'ET' => __('Ethiopia', 'complianz'),
    'FK' => __('Falkland Islands (Malvinas)', 'complianz'),
    'FO' => __('Faroe Islands', 'complianz'),
    'FJ' => __('Fiji', 'complianz'),
    'FI' => __('Finland', 'complianz'),
    'FR' => __('France', 'complianz'),
    'GF' => __('French Guiana', 'complianz'),
    'PF' => __('French Polynesia', 'complianz'),
    'TF' => __('French Southern Territories', 'complianz'),
    'GA' => __('Gabon', 'complianz'),
    'GM' => __('Gambia', 'complianz'),
    'GE' => __('Georgia', 'complianz'),
    'DE' => __('Germany', 'complianz'),
    'GH' => __('Ghana', 'complianz'),
    'GI' => __('Gibraltar', 'complianz'),
    'GR' => __('Greece', 'complianz'),
    'GL' => __('Greenland', 'complianz'),
    'GD' => __('Grenada', 'complianz'),
    'GP' => __('Guadeloupe', 'complianz'),
    'GU' => __('Guam', 'complianz'),
    'GT' => __('Guatemala', 'complianz'),
    'GG' => __('Guernsey', 'complianz'),
    'GN' => __('Guinea', 'complianz'),
    'GW' => __('Guinea-Bissau', 'complianz'),
    'GY' => __('Guyana', 'complianz'),
    'HT' => __('Haiti', 'complianz'),
    'HM' => __('Heard Island & Mcdonald Islands', 'complianz'),
    'VA' => __('Holy See (Vatican City State)', 'complianz'),
    'HN' => __('Honduras', 'complianz'),
    'HK' => __('Hong Kong', 'complianz'),
    'HU' => __('Hungary', 'complianz'),
    'IS' => __('Iceland', 'complianz'),
    'IN' => __('India', 'complianz'),
    'ID' => __('Indonesia', 'complianz'),
    'IR' => __('Iran, Islamic Republic Of', 'complianz'),
    'IQ' => __('Iraq', 'complianz'),
    'IE' => __('Ireland', 'complianz'),
    'IM' => __('Isle Of Man', 'complianz'),
    'IL' => __('Israel', 'complianz'),
    'IT' => __('Italy', 'complianz'),
    'JM' => __('Jamaica', 'complianz'),
    'JP' => __('Japan', 'complianz'),
    'JE' => __('Jersey', 'complianz'),
    'JO' => __('Jordan', 'complianz'),
    'KZ' => __('Kazakhstan', 'complianz'),
    'KE' => __('Kenya', 'complianz'),
    'KI' => __('Kiribati', 'complianz'),
    'KR' => __('Korea', 'complianz'),
    'KW' => __('Kuwait', 'complianz'),
    'KG' => __('Kyrgyzstan', 'complianz'),
    'LA' => __('Lao People\'s Democratic Republic', 'complianz'),
    'LV' => __('Latvia', 'complianz'),
    'LB' => __('Lebanon', 'complianz'),
    'LS' => __('Lesotho', 'complianz'),
    'LR' => __('Liberia', 'complianz'),
    'LY' => __('Libyan Arab Jamahiriya', 'complianz'),
    'LI' => __('Liechtenstein', 'complianz'),
    'LT' => __('Lithuania', 'complianz'),
    'LU' => __('Luxembourg', 'complianz'),
    'MO' => __('Macao', 'complianz'),
    'MK' => __('Macedonia', 'complianz'),
    'MG' => __('Madagascar', 'complianz'),
    'MW' => __('Malawi', 'complianz'),
    'MY' => __('Malaysia', 'complianz'),
    'MV' => __('Maldives', 'complianz'),
    'ML' => __('Mali', 'complianz'),
    'MT' => __('Malta', 'complianz'),
    'MH' => __('Marshall Islands', 'complianz'),
    'MQ' => __('Martinique', 'complianz'),
    'MR' => __('Mauritania', 'complianz'),
    'MU' => __('Mauritius', 'complianz'),
    'YT' => __('Mayotte', 'complianz'),
    'MX' => __('Mexico', 'complianz'),
    'FM' => __('Micronesia, Federated States Of', 'complianz'),
    'MD' => __('Moldova', 'complianz'),
    'MC' => __('Monaco', 'complianz'),
    'MN' => __('Mongolia', 'complianz'),
    'ME' => __('Montenegro', 'complianz'),
    'MS' => __('Montserrat', 'complianz'),
    'MA' => __('Morocco', 'complianz'),
    'MZ' => __('Mozambique', 'complianz'),
    'MM' => __('Myanmar', 'complianz'),
    'NA' => __('Namibia', 'complianz'),
    'NR' => __('Nauru', 'complianz'),
    'NP' => __('Nepal', 'complianz'),
    'NL' => __('Netherlands', 'complianz'),
    'AN' => __('Netherlands Antilles', 'complianz'),
    'NC' => __('New Caledonia', 'complianz'),
    'NZ' => __('New Zealand', 'complianz'),
    'NI' => __('Nicaragua', 'complianz'),
    'NE' => __('Niger', 'complianz'),
    'NG' => __('Nigeria', 'complianz'),
    'NU' => __('Niue', 'complianz'),
    'NF' => __('Norfolk Island', 'complianz'),
    'MP' => __('Northern Mariana Islands', 'complianz'),
    'NO' => __('Norway', 'complianz'),
    'OM' => __('Oman', 'complianz'),
    'PK' => __('Pakistan', 'complianz'),
    'PW' => __('Palau', 'complianz'),
    'PS' => __('Palestinian Territory, Occupied', 'complianz'),
    'PA' => __('Panama', 'complianz'),
    'PG' => __('Papua New Guinea', 'complianz'),
    'PY' => __('Paraguay', 'complianz'),
    'PE' => __('Peru', 'complianz'),
    'PH' => __('Philippines', 'complianz'),
    'PN' => __('Pitcairn', 'complianz'),
    'PL' => __('Poland', 'complianz'),
    'PT' => __('Portugal', 'complianz'),
    'PR' => __('Puerto Rico', 'complianz'),
    'QA' => __('Qatar', 'complianz'),
    'RE' => __('Reunion', 'complianz'),
    'RO' => __('Romania', 'complianz'),
    'RU' => __('Russian Federation', 'complianz'),
    'RW' => __('Rwanda', 'complianz'),
    'BL' => __('Saint Barthelemy', 'complianz'),
    'SH' => __('Saint Helena', 'complianz'),
    'KN' => __('Saint Kitts And Nevis', 'complianz'),
    'LC' => __('Saint Lucia', 'complianz'),
    'MF' => __('Saint Martin', 'complianz'),
    'PM' => __('Saint Pierre And Miquelon', 'complianz'),
    'VC' => __('Saint Vincent And Grenadines', 'complianz'),
    'WS' => __('Samoa', 'complianz'),
    'SM' => __('San Marino', 'complianz'),
    'ST' => __('Sao Tome And Principe', 'complianz'),
    'SA' => __('Saudi Arabia', 'complianz'),
    'SN' => __('Senegal', 'complianz'),
    'RS' => __('Serbia', 'complianz'),
    'SC' => __('Seychelles', 'complianz'),
    'SL' => __('Sierra Leone', 'complianz'),
    'SG' => __('Singapore', 'complianz'),
    'SK' => __('Slovakia', 'complianz'),
    'SI' => __('Slovenia', 'complianz'),
    'SB' => __('Solomon Islands', 'complianz'),
    'SO' => __('Somalia', 'complianz'),
    'ZA' => __('South Africa', 'complianz'),
    'GS' => __('South Georgia And Sandwich Isl.', 'complianz'),
    'ES' => __('Spain', 'complianz'),
    'LK' => __('Sri Lanka', 'complianz'),
    'SD' => __('Sudan', 'complianz'),
    'SR' => __('Suriname', 'complianz'),
    'SJ' => __('Svalbard And Jan Mayen', 'complianz'),
    'SZ' => __('Swaziland', 'complianz'),
    'SE' => __('Sweden', 'complianz'),
    'CH' => __('Switzerland', 'complianz'),
    'SY' => __('Syrian Arab Republic', 'complianz'),
    'TW' => __('Taiwan', 'complianz'),
    'TJ' => __('Tajikistan', 'complianz'),
    'TZ' => __('Tanzania', 'complianz'),
    'TH' => __('Thailand', 'complianz'),
    'TL' => __('Timor-Leste', 'complianz'),
    'TG' => __('Togo', 'complianz'),
    'TK' => __('Tokelau', 'complianz'),
    'TO' => __('Tonga', 'complianz'),
    'TT' => __('Trinidad And Tobago', 'complianz'),
    'TN' => __('Tunisia', 'complianz'),
    'TR' => __('Turkey', 'complianz'),
    'TM' => __('Turkmenistan', 'complianz'),
    'TC' => __('Turks And Caicos Islands', 'complianz'),
    'TV' => __('Tuvalu', 'complianz'),
    'UG' => __('Uganda', 'complianz'),
    'UA' => __('Ukraine', 'complianz'),
    'AE' => __('United Arab Emirates', 'complianz'),
    'GB' => __('United Kingdom', 'complianz'),
    'US' => __('United States', 'complianz'),
    'UM' => __('United States Outlying Islands', 'complianz'),
    'UY' => __('Uruguay', 'complianz'),
    'UZ' => __('Uzbekistan', 'complianz'),
    'VU' => __('Vanuatu', 'complianz'),
    'VE' => __('Venezuela', 'complianz'),
    'VN' => __('Viet Nam', 'complianz'),
    'VG' => __('Virgin Islands, British', 'complianz'),
    'VI' => __('Virgin Islands, U.S.', 'complianz'),
    'WF' => __('Wallis And Futuna', 'complianz'),
    'EH' => __('Western Sahara', 'complianz'),
    'YE' => __('Yemen', 'complianz'),
    'ZM' => __('Zambia', 'complianz'),
    'ZW' => __('Zimbabwe', 'complianz'),
);