<?php
defined('ABSPATH') or die("you do not have acces to this page!");
/*
 * Unique used names must be unique for this service. It is used to link the service to the cookie.
 * used names should contain all used cookie names
 * if match should be made on partial of cookiename only, prefix with "partial_"
 *
 * */
$this->ignore_cookie_list = array('wp-saving-post', 'wp-settings', 'redux_blast', 'wordpress_test_cookie');

$this->known_cookie_keys = array(

    'wordPress_metrics' => array('functional' => true,
        'used_names' => array('tk_lr','tk_or', 'tk_r3d' ),
        'unique_used_names' => array('tk_lr','tk_or', 'tk_r3d'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => "WordPress.com",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("Collection of internal metrics for user activity, used to improve user experience.", 'complianz'),
    ),

    'wordpress' => array(
        'functional' => true,
        'used_names' => array('_wordpress_'),
        'unique_used_names' => array('partial_wordpress_'),
        'label' => "WordPress",
        'privacy_policy_url' => '[privacy_policy_url]',
        'purpose' => __("WordPress log in cookie", 'complianz'),
        'storage_duration' => __("30 days", 'complianz'),
        'description' => __("Cookie to keep you logged in", 'complianz'),
    ),

    'googlemaps' => array(
        'functional' => false,
        'used_names' => array(),
        'unique_used_names' => array(),
        'label' => "Google Maps",
        'privacy_policy_url' => 'https://myaccount.google.com/privacy',
        'purpose' => __("Google Maps cookie", 'complianz'),
        'storage_duration' => __("30 days", 'complianz'),
        'description' => __("Google Maps cookies to track individual users.", 'complianz'),
    ),

    'youtube' => array(
        'functional' => false,
        'used_names' => array(''),
        'unique_used_names' => array(''),
        'label' => "YouTube",
        'privacy_policy_url' => 'https://myaccount.google.com/privacy',
        'purpose' => __("Youtube cookie to track individual users", 'complianz'),
        'storage_duration' => __("30 days", 'complianz'),
        'description' => __("Cookies to track individual users.", 'complianz'),
    ),

    'vimeo' => array(
        'functional' => false,
        'used_names' => array('vuid  ','__utma','__utmt_player', '__utmz','__utmc', '__utmb'),
        'unique_used_names' => array('vuid  ','__utma','__utmt_player'),
        'label' => "Vimeo",
        'privacy_policy_url' => 'https://vimeo.com/privacy',
        'purpose' => __("To display and deliver videos we use Vimeo, a video sharing website. The embedded Vimeo player uses cookies to check if certain features or preferences have been selected by the user.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Cookies to track individual users.", 'complianz'),
    ),

    'videopress' => array('functional' => false,
        'used_names' => array('_utmb', '_utmz', '_utmc', '_utma'),
        'unique_used_names' => array(),
        'privacy_policy_url' => 'https://automattic.com/privacy/',
        'label' => "VideoPress",
        'purpose' => __("Display and host video's", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Display and host videos", 'complianz'),
    ),

    'dailymotion' => array('functional' => false,
        'used_names' => array('dmvk', 'hist', 's_vi', 'ts', 'v1st'),
        'unique_used_names' => array('dmvk', 'hist', 's_vi', 'ts', 'v1st'),
        'privacy_policy_url' => 'https://www.dailymotion.com/legal/privacy',
        'label' => "Dailymotion",
        'purpose' => __("Display and host video's", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Display and host videos", 'complianz'),
    ),

    'google-analytics' => array(
        'functional' => true,
        'used_names' => array('_ga', '_gid', '_gat', '_gaexp', '_utm', '__utmc', 'UTMD_', '__utmv', '__utmz', '_gat_gtag_UA_ID'),
        'unique_used_names' => array('partial_gat_UA', '_ga', '_gaexp', '_gid', '_gat', 'partial_utm', '__utmb', '__utmc', 'UTMD__', '__utmv', '__utmz', '_gat_gtag_UA_ID'),
        'privacy_policy_url' => 'https://policies.google.com/privacy',
        'label' => "Google Analytics",
        'purpose' => __("Performance", 'complianz'),
        'storage_duration' => __("From session up to  two years", 'complianz'),
        'description' => __("We use Google Analytics, a web analytics service provided by Google. Google Analytics uses cookies that allows us to analyze the use of our website and to compile reports on website activity and internet usage.", 'complianz'),
    ),

    'google-fonts' => array(
        'functional' => false,
        'used_names' => array(),
        'unique_used_names' => array(),
        'privacy_policy_url' => 'https://policies.google.com/privacy',
        'label' => "Google Fonts",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'google-recaptcha' => array(
        'functional' => false,
        'used_names' => array(),
        'unique_used_names' => array(),
        'privacy_policy_url' => 'https://policies.google.com/privacy',
        'label' => "Google Recaptcha",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'mixpanel' => array(
        'functional' => true,
        'used_names' => array('mixpanel'),
        'unique_used_names' => array('partial_mixpanel'),
        'privacy_policy_url' => '',
        'label' => __("Mixpanel", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'matomo' => array(
        'functional' => true,
        'used_names' => array('_pk_ref', '_pk_cvar', '_pk_id', '_pk_ses', '_pk_hsr', 'piwik_ignore', 'PIWIK_SESSID'),
        'unique_used_names' => array('partial__pk_', 'partial_piwik', 'PIWIK_SESSID'),
        'privacy_policy_url' => 'https://matomo.org/privacy-policy/',
        'label' => "Matomo",
        'purpose' => __("Track statistics", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Track statistics for the website", 'complianz'),
    ),

    'php-session' => array('functional' => true,
        'used_names' => array('PHPSESSID'),
        'unique_used_names' => array('PHPSESSID'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => "PHP Session ID",
        'purpose' => __("Storing user data across pages for functional purposes", 'complianz'),
        'storage_duration' => __("Store data for users to use in the web application", 'complianz'),
        'description' => __("Sessions are a simple way to store data for individual users against a unique session ID. Session IDs are sent to the browser via session cookies and the ID is used to retrieve existing session data", 'complianz'),
    ),
    'stripe' => array('functional' => true,
        'used_names' => array('__stripe_mid', '__stripe_sid'),
        'unique_used_names' => array('__stripe_mid', 'partial__stripe_'),
        'privacy_policy_url' => 'https://stripe.com/privacy/',
        'label' => __("Stripe payment gateway", 'complianz'),
        'purpose' => __("Fraud prevention", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("Stripe uses cookies to prevent fraud", 'complianz'),
    ),

    'complianz' => array('functional' => true,
        'used_names' => array('cmplz_all', 'cmplz_event_xxx','cmplz_stats', 'cmplz_id','complianz_config', 'complianz_consent_status', 'complianz_policy_id'),
        'unique_used_names' => array('cmplz_all','partial_cmplz_', 'complianz_config','cmplz_id', 'cookieconsent_status', 'complianz_consent_status', 'complianz_policy_id'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => "Complianz",
        'purpose' => __("Remember the cookie warning choice", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Complianz stores the user preferences for the cookie warning banner", 'complianz'),
    ),

    'affiliatewp' => array(
        'functional' => true,
        'used_names' => array('affwp_ref'),
        'unique_used_names' => array('affwp_ref'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => "Affiliate WP",
        'purpose' => __("track users to be able to pay a commission to affiliates", 'complianz'),
        'storage_duration' => __("30 days", 'complianz'),
        'description' => __("Affiliate WP tracks visits from users to be able to pay the affiliate a commission for a sale by a user coming from an affiliate's website.", 'complianz'),
    ),
    'add-this' => array('functional' => false,
        'used_names' => array('__atuvs', '__atuvc', 'psc', 'uid', 'uit', 'uvc', 'cw_id', 'loc', 'mus', 'na_id', 'na_tc', 'uvc', 'uid', 'ouid'),
        'unique_used_names' => array('__atuvs', '__atuvc', 'cw_id', 'na_id'),
        'privacy_policy_url' => 'https://addthis.com',
        'label' => "Add This",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'aelia_currency' => array('functional' => true,
        'used_names' => array('aelia_cs_selected_currency'),
        'unique_used_names' => array('aelia_cs_selected_currency'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => "Currency preference",
        'purpose' => __("Currency selection storage", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Store user preference for the selected currency", 'complianz'),
    ),

    'adyen' => array('functional' => false,
        'used_names' => array('hppsession'),
        'unique_used_names' => array('hppsession'),
        'privacy_policy_url' => 'https://adyen.com',
        'label' => "Adyen",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'facebook' => array('functional' => false,
        'used_names' => array('fbm_', 'actppresence', 'sb', 'csm', 'c_user', 'frstxs', 'datr', '_fbp'),
        'unique_used_names' => array('partial_fbm_', 'actppresence', 'sb', 'csm', 'c_user', 'frstxs', 'datr', '_fbp'),
        'privacy_policy_url' => 'https://www.facebook.com/policy/cookies',
        'label' => "Facebook",
        'purpose' => __("Personalised advertisements", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Facebook uses cookies to target users with personalised advertisements", 'complianz'),
    ),

    'instagram' => array(
        'functional' => false,
        'used_names' => array('fbm_', 'actppresence', 'sb', 'csm', 'c_user', 'frstxs', 'datr', '_fbp'),
        'unique_used_names' => array('partial_fbm_', 'actppresence', 'sb', 'csm', 'c_user', 'frstxs', 'datr', '_fbp'),
        'privacy_policy_url' => 'https://www.instagram.com/legal/cookies/',
        'label' => "Instagram",
        'purpose' => __("Personalised advertisements", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Instagram uses cookies to target users with personalised advertisements", 'complianz'),
    ),

    'criteo' => array('functional' => false,
        'used_names' => array('hid', 'has_js', 'tk', 'uic', 'ect', 'udc', 'dis', 'udi'),
        'unique_used_names' => array('hid', 'has_js', 'tk', 'uic', 'ect', 'udc', 'dis', 'udi'),
        'privacy_policy_url' => 'https://criteo.com',
        'label' => "Criteo",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'google' => array('functional' => false,
        'used_names' => array('PREF', 'NID', 'id', '_drt_', 'HSID', 'SSIDAPISID', 'SAPISID', '__ut','OGPC', 'SID', 'HSID', 'SSID', 'APISID', 'SNID','CONSENT'),
        'unique_used_names' => array('PREF', 'NID', '_drt_', 'HSID', 'SSIDAPISID', 'SAPISID', '__ut','OGPC', 'SID', 'HSID', 'SSID', 'APISID', 'SNID','CONSENT'),
        'privacy_policy_url' => 'https://policies.google.com/privacy',
        'label' => __("Google Ads Optimization", 'complianz'),
        'purpose' => __("Personalised advertisements", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Google tracks users across platforms to target users with highly personalised ads", 'complianz'),
    ),

    'googleplus' => array(
        'functional' => false,
        'used_names' => array('OGPC', 'SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'CONSENT', 'SNID', 'NID'),
        'unique_used_names' => array(),
        'privacy_policy_url' => 'https://myaccount.google.com/privacy',
        'label' => __("Google Plus", 'complianz'),
        'purpose' => __("The Google Plus cookie tracks visitors’ browsing behavior for ad purposes and timeline optimization. It also provides the possibility to share information.", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Google Plus is a social network website that runs on Google technology. More than 500 million users are registered for this channel, which makes it the second largest social network website. Registered users can share information such as links, images and videos with friends.", 'complianz'),
    ),

    'cloudflare' => array('functional' => false,
        'used_names' => array('__cfduid', '_sm_au_c'),
        'unique_used_names' => array('__cfduid', '_sm_au_c'),
        'privacy_policy_url' => 'https://www.cloudflare.com/privacypolicy/',
        'label' => "CloudFlare",
        'purpose' => __("Security and webspeed by delivering content from a distributed servers.", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("The __cfduid cookie is used to identify individual clients behind a shared IP address and apply security settings on a per-client basis. ", 'complianz'),
    ),

    'whatsapp' => array(
        'functional' => false,
        'used_names' => array(''),
        'unique_used_names' => array(''),
        'privacy_policy_url' => 'https://www.whatsapp.com/legal/#privacy-policy',
        'label' => "Whatsapp",
        'purpose' => __("WhatsApp is a cross platform service suited for smartphones and computers, protected by end to end encryption.", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("The WhatsApp cookie makes it possible to share information with visitors’ friends & others.", 'complianz'),
    ),

    'salesforce-liveagent' => array('functional' => false,
        'used_names' => array('liveagent_oref', 'liveagent_sid', 'liveagent_vc', 'liveagent_ptid'),
        'unique_used_names' => array('partial_liveagent_'),
        'privacy_policy_url' => 'https://www.salesforce.com/company/privacy/',
        'label' => "Salesforce Liveagent",
        'purpose' => __("Real-time chat cookie", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to chat real-time with employees.", 'complianz'),
    ),

    'livechat' => array('functional' => false,
        'used_names' => array('hide_eye_catcher','autoinvite_callback','__lc.visitor_id', 'hide_eye_catcher', 'autoinvite_callback', '__lc.visitor_id', 'lc_invitation_opened', 'lc_window_state', 'lc_sso9818825', '__lc_visitor_id'),
        'unique_used_names' => array('hide_eye_catcher','autoinvite_callback','wpfront-notification-bar-landingpage', 'partial__lc.visitor_id', 'partial_lc_'),
        'privacy_policy_url' => 'https://www.livechat.com/privacy/',
        'label' => "Livechat",
        'purpose' => __("Real-time chat cookie", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Live Chat is a chat system which can help users with questions regarding our products and website.", 'complianz'),
    ),

    'doubleclick' => array('functional' => false,
        'used_names' => array('idIDE', 'test_cookie', 'id', '___gads', '_drt_', 'DSID', 'IDE', 'ar_v4'),
        'unique_used_names' => array('idIDE', 'DSID', 'ar_v4'),
        'privacy_policy_url' => 'https://policies.google.com/privacy',
        'label' => __("DoubleCLick", 'complianz'),
        'purpose' => __("Advertisement", 'complianz'),
        'storage_duration' => __("2 years", 'complianz'),
        'description' => __("This cookie from Doubleclick.net helps us to understand the products you are viewing. We can show you relevant advertisements on our (partner) sites. We can also keep track of how many times you've seen an ad, whether you click on an ad and whether you place an order if you clicked on an ad.", 'complianz'),
    ),

    'optimizely' => array('functional' => false,
        'used_names' => array('end_user_id', 'cdnoptimizely', 'ab_optimizely', 'optimizelyPendingLogEvents', 'optimizelyEndUserId', 'optimizelySegments',  'optimizelyBuckets', 'optimizelyPPID' ),
        'unique_used_names' => array('cdnoptimizely', 'ab_optimizely'),
        'privacy_policy_url' => 'https://www.optimizely.com/privacy/',
        'label' => __("Optimizely", 'complianz'),
        'purpose' => __("Performance", 'complianz'),
        'storage_duration' => __("From session up to ten years", 'complianz'),
        'description' => __("Optimizely is a service that enables us to test the effectiveness of different versions of our website and/or content (A/B-testing). The cookies which are set may record your surf and click behavior and other activity." , 'complianz'),
    ),

    'hotjar' => array('functional' => false,
        'used_names' => array('_hjUserId', '_hjIncludedInSample', '_hjMinimizedTestersWidgets', '_hjClosedSurveyInvites', '_hjDonePolls', '_hjMinimizedPolls', '_hjDoneTestersWidgets'),
        'unique_used_names' => array('_hjUserId', '_hjIncludedInSample', '_hjMinimizedTestersWidgets', '_hjClosedSurveyInvites', '_hjDonePolls', '_hjMinimizedPolls', '_hjDoneTestersWidgets'),
        'privacy_policy_url' => '',
        'label' => __("Hotjar", 'complianz'),
        'purpose' => __("Performance", 'complianz'),
        'storage_duration' => __("session", 'complianz'),
        'description' => __("On this website, we use Analytics and services from  Hotjar, a company based in Malta. HotJar helps us gain insight into how our website is used. We place this cookie ourselves.", 'complianz'),
    ),

    'visual-website-optimizer' => array('functional' => false,
        'used_names' => array('_vis_opt_out', '_vis_opt_s', 'partial_vis_opt_exp', '_vis_opt_test_cookie', '_vis_opt_exp_[experiment_id]_goal_[goal_id]', 'partial_vwo_', '_vwo_uuid_v2'),
        'unique_used_names' => array('_vwo_uuid_v2'),
        'privacy_policy_url' => '',
        'label' => __("Visual Website Optimizer", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'snoobi' => array('functional' => false,
        'used_names' => array('Snoobisession_adcalls_nl', 'SnoobiID', 'Snoop_testi'),
        'unique_used_names' => array('Snoobisession_adcalls_nl', 'SnoobiID', 'Snoop_testi'),
        'privacy_policy_url' => '',
        'label' => __("Snoobi", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'adcalls' => array('functional' => false,
        'used_names' => array('acalltracker', 'acalltrackersession'),
        'unique_used_names' => array('acalltracker', 'acalltrackersession'),
        'privacy_policy_url' => '',
        'label' => __("Adcalls", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'call-tracking-metrics' => array('functional' => false,
        'used_names' => array('ctm'),
        'unique_used_names' => array('ctm'),
        'privacy_policy_url' => '',
        'label' => __("Call Tracking Metrics", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'tealium' => array('functional' => false,
        'used_names' => array('utag_main'),
        'unique_used_names' => array('utag_main'),
        'privacy_policy_url' => '',
        'label' => __("Tealium", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'adkernel' => array('functional' => false,
        'used_names' => array('ADK_EX_15', 'ADKUID'),
        'unique_used_names' => array('ADK_EX_15', 'ADKUID'),
        'privacy_policy_url' => '',
        'label' => __("Adkernel", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'gigya-com' => array('functional' => false,
        'used_names' => array('gig_hasGmid'),
        'unique_used_names' => array('gig_hasGmid'),
        'privacy_policy_url' => '',
        'label' => __("Gigya.com", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'casalemedia-com' => array('functional' => false,
        'used_names' => array('CMDD', 'CMRUM3', 'CMSC'),
        'unique_used_names' => array('CMDD', 'CMRUM3', 'CMSC'),
        'privacy_policy_url' => '',
        'label' => __("casalemedia.com", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'demdex-net' => array('functional' => false,
        'used_names' => array('dextp'),
        'unique_used_names' => array('dextp'),
        'privacy_policy_url' => '',
        'label' => __("demdex.net", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'everesttech-net' => array(
      'functional' => false,
        'used_names' => array('everest_g_v2', 'everest_session_v2', 'ev_sync_dd'),
        'unique_used_names' => array('everest_g_v2', 'everest_session_v2', 'ev_sync_dd'),
        'privacy_policy_url' => '',
        'label' => __("everesttech.net", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'mathtag-com' => array('functional' => false,
        'used_names' => array('uuid', 'uuidc', 'HRL8'),
        'unique_used_names' => array('HRL8'),
        'privacy_policy_url' => '',
        'label' => __("mathtag.com", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'zopim' => array('functional' => false,
        'used_names' => array('__zlcmid', '__zprivacy'),
        'unique_used_names' => array('__zlcmid', '__zprivacy', '__zlcprivacy'),
        'privacy_policy_url' => 'https://www.zendesk.com/company/customers-partners/privacy-policy/',
        'label' => __("Zopim", 'complianz'),
        'purpose' => __("Security", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("to identify trusted webtraffic", 'complianz'),
    ),

    'linkedin' => array('functional' => false,
        'used_names' => array('X-LI-IDC'),
        'unique_used_names' => array('X-LI-IDC'),
        'privacy_policy_url' => 'https://www.linkedin.com/legal/privacy-policy',
        'label' => __("Linkedin", 'complianz'),
        'purpose' => __("Linkedin places cookies to track users", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'twitter' => array('functional' => false,
        'used_names' => array('metrics_token'),
        'unique_used_names' => array('metrics_token'),
        'privacy_policy_url' => 'https://twitter.com/en/privacy',
        'label' => __("Twitter", 'complianz'),
        'purpose' => __("Target users with personalised ads", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Twitter tracks users to target them with personalised ads", 'complianz'),
    ),

    'sharethis' => array('functional' => false,
        'used_names' => array('__stid', 'uset', '_utmb', '_utmz', '_utmc', '_utma', 'optimizelyPendingLogEvents', 'optimizelyBuckets', 'optimizelySegments', 'optimizelyEndUserId', '__uset', 'stdlxmap', '_stacxiommap', '_stamap', '_stgmap', '_stid', 'UID', 'UIDR'),
        'unique_used_names' => array('__sharethis_cookie_test__'),
        'privacy_policy_url' => '',
        'label' => __("Share this", 'complianz'),
        'purpose' => __("Target users with personalised ads", 'complianz'),
        'storage_duration' => __("1 year", 'complianz'),
        'description' => __("Share this gathers information on users to target them with personalised ads", 'complianz'),
    ),

    'jetpack' => array('functional' => false,
        'used_names' => array('tk_tc', 'tk_qs', 'tk_ai'),
        'unique_used_names' => array('tk_tc', 'tk_qs', 'tk_ai'),
        'privacy_policy_url' => '',
        'label' => __("JetPack", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'newrelic' => array('functional' => false,
        'used_names' => array('NRMLID', 'NRMPID', 'NRREFL', 'NRREFP', 'optimizelyEndUserId', 'optimizelySegments', 'optimizelyBuckets', '__qca', '__ar_v4', '_biz_uid', '_biz_sid', '_biz_nA', '_biz_pendingA', '_ceg.s', '_ceg.u', 'ajs_user_id', 'ajs_group_id', 'ajs_anonymous_id', '__distillery', '_mkto_trk', 'ei_client_id', 'wcsid', 'hblid', '_oklv', '_okdetect', 'olfsk', '_okbk', '_ok', 'optimizelyPendingLogEvents', '_gal'),
        'unique_used_names' => array('NRMLID', 'NRMPID', 'NRREFL', 'NRREFP'),
        'privacy_policy_url' => '',
        'label' => __("Newrelic", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'slimstat' => array('functional' => false,
        'used_names' => array('slimstat_tracking_code'),
        'unique_used_names' => array('slimstat_tracking_code'),
        'privacy_policy_url' => '',
        'label' => __("Slimstat Tracking Code", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'wpdiscuz_last_visit' => array('functional' => false,
        'used_names' => array('wpdiscuz_last_visit'),
        'unique_used_names' => array('wpdiscuz_last_visit'),
        'privacy_policy_url' => '',
        'label' => __("WP Discuz", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

      'wpml' => array('functional' => true,
        'used_names' => array('wpml_browser_redirect_test', '_icl_current_language', '_icl_visitor_lang_js', '_icl_current_admin_language_', ),
        'unique_used_names' => array('partial_wpml', 'partial__icl_', '_icl_visitor_lang_js'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("WPML", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("WPML is a cookie used to provide different languages for an user. Also it checks which language a user is using.", 'complianz'),
    ),


    'heap' => array('analytical' => true,
        'used_names' => array('_hp2_ses' ),
        'unique_used_names' => array('partial_hp2'),
        'privacy_policy_url' => 'https://heapanalytics.com/privacy',
        'label' => __("Heap Analytics", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("The Heap cookie captures every user interaction from web, mobile, and cloud services.", 'complianz'),
    ),

    'wordfence' => array(
        'functional' => true,
        'used_names' => array('wfvt_3883187383', 'wordfence_verifiedHuman', 'wfwaf-authcookie', 'wfwaf-authcookie-partial_'),
        'unique_used_names' => array('partial_wfvt_','wordfence_verifiedHuman', 'wfwaf-authcookie', 'wfwaf-authcookie-partial_'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("WordFence", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("Tracks a user duration so that so that the page views can be grouped together.", 'complianz'),
    ),

    'mouseflow' => array('analytical' => true,
        'used_names' => array('partial_mf' ),
        'unique_used_names' => array('partial_mf'),
        'privacy_policy_url' => 'https://mouseflow.com/privacy/',
        'label' => __("MouseFlow", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("A cookie for checking if the user is new or returning.", 'complianz'),
    ),

    'sumo' => array('analytical' => true,
        'used_names' => array('__smVID', '__smToken', 'partial_smSessionId', '__smScrollBoxShown', '__smListBuilderShown' ),
        'unique_used_names' => array('__smVID', '__smToken', 'partial_smSessionId', '__smScrollBoxShown', '__smListBuilderShown'),
        'privacy_policy_url' => 'https://help.sumo.com/hc/en-us/articles/218958727-Privacy-Policy',
        'label' => __("Sumo", 'complianz'),
        'purpose' => __("Offer sharing options in a website", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Sumo uses cookies to control many different things in users browsers. These cookies control everything from determining if a visitor is opted-out of a certain popup to telling Sumo whether or not to display a Bar. ", 'complianz'),
    ),
    'googleanalyticsdashboard' => array('analytical' => true,
        'used_names' => array('gadwp_wg_default_metric', 'gadwp_wg_default_dimension', 'gadwp_wg_default_swmetric'),
        'unique_used_names' => array('gadwp_wg_default_metric', 'gadwp_wg_default_dimension', 'gadwp_wg_default_swmetric'),
        'privacy_policy_url' => 'https://exactmetrics.com/privacy-policy/',
        'label' => __("GA - Dashboard", 'complianz'),
        'purpose' => __("This cookie tracks visitor behavior, visited pages etc. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("We use Google Analytics via a Dashboard: a web analytics service provided by Google. Google Analytics uses cookies that allows us to analyze the use of our website and to compile reports on website activity and internet usage. ", 'complianz'),
    ),
    'siteorigin' => array(
        'functional' => true,
        'used_names' => array('siteorigin_panels_live_editor'),
        'unique_used_names' => array('siteorigin_panels_live_editor'),
        'privacy_policy_url' => 'https://siteorigin.com',
        'label' => __("Site Origin", 'complianz'),
        'purpose' => __("This cookie makes it possible to make live changes to an online environment. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible for us to make live changes to the website via a simple Page Builder plugin.", 'complianz'),
    ),
    'Page-ID' => array(
        'functional' => true,
        'used_names' => array('page_id'),
        'unique_used_names' => array('page_id'),
        'privacy_policy_url' => '',
        'label' => __("Page ID", 'complianz'),
        'purpose' => __("This cookie makes it possible to label several pages. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible for us to label several pages in our website.", 'complianz'),
    ),

    'Preview' => array(
        'functional' => true,
        'used_names' => array('preview'),
        'unique_used_names' => array('preview'),
        'privacy_policy_url' => '',
        'label' => __("Preview", 'complianz'),
        'purpose' => __("This cookie makes it possible to preview several pages for admins. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible for us preview several pages.", 'complianz'),
    ),

    'Viewed-Cookie-Policy' => array(
        'analytical' => true,
        'used_names' => array('viewed_cookie_policy'),
        'unique_used_names' => array('viewed_cookie_policy'),
        'privacy_policy_url' => '',
        'label' => __("Preview", 'complianz'),
        'purpose' => __("This cookie makes it possible for us to keep track on who viewed the cookie policy. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible for us to keep track on who viewed the cookie policy.", 'complianz'),
    ),

    'Customize' => array(
        'functional' => true,
        'used_names' => array('customize_changeset_uuid', 'customize_theme', 'customize_messenger_channel', 'customize_autosaved'),
        'unique_used_names' => array('customize_changeset_uuid', 'customize_theme', 'customize_messenger_channel', 'customize_autosaved'),
        'privacy_policy_url' => '',
        'label' => __("Customize", 'complianz'),
        'purpose' => __("This cookie makes it possible for us to customize themes, messenger channels etc. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible for us to customize themes, messenger channels etc.", 'complianz'),
    ),

    'Easy-Digital-Downloads' => array(
        'functional' => true,
        'used_names' => array('edd_remove_from_cart_nonce'),
        'unique_used_names' => array('edd_remove_from_cart_nonce'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Remove item from cart", 'complianz'),
        'purpose' => __("This cookie makes it possible to remove an article from your cart.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible to remove an article from your cart.", 'complianz'),
    ),

    'WF-Waf' => array('functional' => true,
        'used_names' => array('wfwaf-authcookie-id'),
        'unique_used_names' => array('wfwaf-authcookie-id'),
        'privacy_policy_url' => '',
        'label' => __("WFWaf", 'complianz'),
        'purpose' => __("This cookie makes it possible to save choices during your visit.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible to save choices during your visit.", 'complianz'),
    ),

    '1P-Google' => array('functional' => true,
        'used_names' => array('1P_JAR'),
        'unique_used_names' => array('1P_JAR'),
        'privacy_policy_url' => 'https://myaccount.google.com/privacy',
        'label' => __("1P Google", 'complianz'),
        'purpose' => __("This cookie makes it possible to show advertisements based on your search behavior on Google.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie makes it possible to show advertisements based on your search behavior on Google.", 'complianz'),
    ),

    'MailMunch' => array('marketing' => true,
        'used_names' => array('mailmunch_second_pageview'),
        'unique_used_names' => array('mailmunch_second_pageview'),
        'privacy_policy_url' => 'https://legal.mailmunch.com/privacy/',
        'label' => __("MailMunch", 'complianz'),
        'purpose' => __("This cookie is used to manage subscription services to mailing lists of blogs.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to manage subscription services to mailing lists of blogs.", 'complianz'),
    ),

    'MailChimp' => array('marketing' => true,
        'used_names' => array('mailchimp_landing_site', 'mailchimp.cart.current_email', 'mailchimp.cart.previous_email', 'mailchimp_user_email', 'mailchimp_user_previous_email', 'mailchimp_cart_current_email', 'mailchimp_cart_previous_email'),
        'unique_used_names' => array('mailchimp_landing_site', 'mailchimp.cart.current_email', 'mailchimp.cart.previous_email', 'mailchimp_user_email', 'mailchimp_user_previous_email', 'mailchimp_cart_current_email', 'mailchimp_cart_previous_email'),
        'privacy_policy_url' => 'https://mailchimp.com/legal/privacy/',
        'label' => __("MailChimp", 'complianz'),
        'purpose' => __("This cookie is used to keep track of newsletter sign ups.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("These cookies are used to keep track of newsletter sign ups and client emails at checkout, Mailchimp utilises cookies to store information captured from user input for remarketing purpose.", 'complianz'),
    ),

    'Clicky-Web-Analytics' => array('functional' => true,
        'used_names' => array('_jsuid'),
        'unique_used_names' => array('_jsuid'),
        'privacy_policy_url' => 'https://www.optimizely.com/privacy/',
        'label' => __("Clicky", 'complianz'),
        'purpose' => __("This cookie is used to identify new or unique visitors.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to identify new or unique visitors.", 'complianz'),
    ),

    'Hubspot' => array('functional' => true,
        'used_names' => array('hubspotutk', '__hssrc', '__hssc', '__hstc'),
        'unique_used_names' => array('hubspotutk', '__hssrc', '__hssc', '__hstc'),
        'privacy_policy_url' => 'https://legal.hubspot.com/privacy-policy',
        'label' => __("Clicky", 'complianz'),
        'purpose' => __("This cookie is used to track visitors, keep track of sessions and recognize visitors.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to track visitors, keep track of sessions and recognize visitors.", 'complianz'),
    ),

    'Fullstory' => array('functional' => true,
        'used_names' => array('fs_uid'),
        'unique_used_names' => array('fsuid'),
        'privacy_policy_url' => 'https://www.fullstory.com/legal/privacy/',
        'label' => __("Clicky", 'complianz'),
        'purpose' => __("This cookie is used by FullStory to track sessions.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used by FullStory to track sessions.", 'complianz'),
    ),

    'Quantcast' => array('marketing' => true,
        'used_names' => array('qca'),
        'unique_used_names' => array('qca'),
        'privacy_policy_url' => 'https://www.quantcast.com/privacy/',
        'label' => __("Clicky", 'complianz'),
        'purpose' => __("This cookie is used by Quantcast to segmentate audiences and do targeted advertising.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used by Quantcast to segmentate audiences and do targeted advertising.", 'complianz'),
    ),

    'Metorik-Sourcebuster' => array('functional' => true,
        'used_names' => array('metorik_http_referer', '	sbjs_current', 'sbjs_current_add', 'sbjs_first', 'sbjs_first_add', 'sbjs_migrations', 'sbjs_session', 'sbjs_udata'),
        'unique_used_names' => array('metorik_http_referer', '	sbjs_current', 'sbjs_current_add', 'sbjs_first', 'sbjs_first_add', 'sbjs_migrations', 'sbjs_session', 'sbjs_udata'),
        'privacy_policy_url' => 'https://www.quantcast.com/privacy/',
        'label' => __("Metorik", 'complianz'),
        'purpose' => __("This cookie is used to deliver a shopping cart and make it work, and also takes care of product statistics.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to deliver a shopping cart and make it work, and also takes care of product statistics.", 'complianz'),
    ),

    'WP-Engine' => array('functional' => true,
        'used_names' => array('wpe_test_group', 'wpe-auth'),
        'unique_used_names' => array('wpe_test_group', 'wpe-auth'),
        'privacy_policy_url' => 'https://wpengine.com/legal/privacy/',
        'label' => __("WP-Engine", 'complianz'),
        'purpose' => __("This cookie is used to analyse the website.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to analyse the website.", 'complianz'),
    ),

    'XSRF-TOKEN' => array('functional' => true,
        'used_names' => array('XSRF-TOKEN'),
        'unique_used_names' => array('XSRF-TOKEN'),
        'privacy_policy_url' => '/',
        'label' => __("XSRF-TOKEN", 'complianz'),
        'purpose' => __("This cookie is written to help with site security in preventing Cross-Site Request Forgery attacks.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is written to help with site security in preventing Cross-Site Request Forgery attacks.", 'complianz'),
    ),

    'WooCommerce' => array('functional' => true,
        'used_names' => array('wc_cart_hash_xxxxxx','wpwoocommerce_session_partial_', 'woocommerce_recently_viewed', 'woocommerce_items_in_cart', 'woocommerce_cart_hash', 'wp_woocommerce_session_b9b4acba601b59ea5524bc3d8671ed71'),
        'unique_used_names' => array('wc_partial_', 'wpwoocommerce_session_partial_', 'woocommerce_recently_viewed', 'woocommerce_items_in_cart', 'woocommerce_cart_hash', 'wp_woocommerce_session_b9b4acba601b59ea5524bc3d8671ed71'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("WooCommerce", 'complianz'),
        'purpose' => __("This cookie is placed to keep track of sales, shopping cart items.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is placed to keep track of sales, shopping cart items.", 'complianz'),
    ),

    'WPForms' => array('functional' => true,
        'used_names' => array('_wpfuuid'),
        'unique_used_names' => array('_wpfuuid'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("WPForms", 'complianz'),
        'purpose' => __("This cookie is placed to place contact forms and follow submissions.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is placed to place contact forms and follow submissions.", 'complianz'),
    ),

    'Beeketing' => array('functional' => true,
        'used_names' => array('_beeketing_cart_token', 'beeketing_show_review_request', 'beeketing_show_cross_sell', 'bk_show_tab_freeApps', 'bk_abtest_last_changed_time', 'bk_identify', 'bk_cart'),
        'unique_used_names' => array('_beeketing_cart_token', 'beeketing_show_review_request', 'beeketing_show_cross_sell', 'bk_show_tab_freeApps', 'bk_abtest_last_changed_time', 'bk_identify', 'bk_cart'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Beeketing", 'complianz'),
        'purpose' => __("Beeketing uses cookies to enhance our users' and customers' experience on the internet.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("TBeeketing uses cookies to enhance our users' and customers' experience on the internet.", 'complianz'),
    ),

    'WPSmush' => array('functional' => true,
        'used_names' => array('_drip_client_6994213'),
        'unique_used_names' => array('_drip_client_6994213'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("WPSmush", 'complianz'),
        'purpose' => __("WPSmush uses cookies to compress images to be able to have lower loading time.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("WPSmush uses cookies to compress images to be able to have lower loading time.", 'complianz'),
    ),

    'Cookie_Consent_Cookiebot' => array('functional' => true,
        'used_names' => array('CookieConsent'),
        'unique_used_names' => array('CookieConsent'),
        'privacy_policy_url' => 'https://www.cookiebot.com/en/privacy-policy/',
        'label' => __("CookieBot", 'complianz'),
        'purpose' => __("CookieBot uses cookies to be able to set up a cookie banner and block & place cookies.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("CookieBot uses cookies to be able to set up a cookie banner and block & place cookies.", 'complianz'),
    ),

    'Pop_Up_Maker' => array('marketing' => true,
        'used_names' => array('pum-partial_'),
        'unique_used_names' => array('pum-partial_'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Pop Up Maker", 'complianz'),
        'purpose' => __("This is a WordPress plugin that is able to show popups while browsing on a website.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This is a WordPress plugin that is able to show popups while browsing on a website.", 'complianz'),
    ),
    'fomify' => array('marketing' => true,
        'used_names' => array('ibx_wpfomo_ip'),
        'unique_used_names' => array('ibx_wpfomo_ip'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Fomify", 'complianz'),
        'purpose' => __("This is a WordPress plugin that is able to show popups containing information of recent purchases.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This is a WordPress plugin that is able to show popups containing information of recent purchases.", 'complianz'),
    ),

    'Tawk' => array('marketing' => true,
        'used_names' => array('__tawkuuid', 'TawkConnectionTime', 'tawkUUID', 'tawk-partial_'),
        'unique_used_names' => array('__tawkuuid', 'TawkConnectionTime', 'tawkUUID', 'tawk-partial_'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Tawk", 'complianz'),
        'purpose' => __("Tawk is a chatservice. It uses cookies to be able to assist you at any time.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Tawk is a chatservice. It uses cookies to be able to assist you at any time.", 'complianz'),
    ),

    'Polylang' => array('functional' => true,
        'used_names' => array('pll_language'),
        'unique_used_names' => array('pll_language'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Polylang", 'complianz'),
        'purpose' => __("This cookie determines which language should be used on the website.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie determines which language should be used on the website.", 'complianz'),
    ),

    'EU_Cookie_Law' => array('functional' => true,
        'used_names' => array('eucookielaw'),
        'unique_used_names' => array('eucookielaw'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("EU Cookie Law", 'complianz'),
        'purpose' => __("The EU Cookie Law plugin is a plugin that places cookies to be able to show a cookie banner.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("The EU Cookie Law plugin is a plugin that places cookies to be able to show a cookie banner.", 'complianz'),
    ),

    'GDPR_Plugin' => array(
        'functional' => true,
        'used_names' => array('gdpr', 'gdpr[consent_types]', 'gdpr[allowed_cookies]', 'gdpr[privacy_bar]', 'cookie_notice_accepted', 'cookies_accepted'),
        'unique_used_names' => array('gdpr', 'gdpr[consent_types]', 'gdpr[allowed_cookies]', 'gdpr[privacy_bar]', 'cookie_notice_accepted', 'cookies_accepted'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("GDPR Plugin", 'complianz'),
        'purpose' => __("The GDPR plugin is a plugin that places cookies to help DPOs in making a website compliant.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("The GDPR plugin is a plugin that places cookies to help DPOs in making a website compliant.", 'complianz'),
    ),
    'ThriveLeads' => array('marketing' => true,
        'used_names' => array('tl_conversion', 'tl-conv-partial_'),
        'unique_used_names' => array('tl_conversion', 'tl-conv-partial_'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Thrive Leads", 'complianz'),
        'purpose' => __("This plugin assists website owners in getting more conversions via e-mail marketing.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This plugin assists website owners in getting more conversions via e-mail marketing.", 'complianz'),
    ),

    'Contact_Form_plugin' => array('functional' => true,
        'used_names' => array('vchideactivationmsg_vc11'),
        'unique_used_names' => array('vchideactivationmsg_vc11'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Contact Form", 'complianz'),
        'purpose' => __("This cookie aids in sending messages via the Contact Form plugin.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie aids in sending messages via the Contact Form plugin.", 'complianz'),
    ),

    '240Plan' => array('functional' => true,
        'used_names' => array('240plan', '240planBAK'),
        'unique_used_names' => array('240plan', '240planBAK'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("240 Plan", 'complianz'),
        'purpose' => __("This cookie aids in being able to fall back on the server which hosts this website.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie aids in being able to fall back on the server which hosts this website.", 'complianz'),
    ),

    'ithemes-Security' => array('functional' => true,
        'used_names' => array('itsec-hb-login-partial_'),
        'unique_used_names' => array('itsec-hb-login-partial_'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("IThemes Security", 'complianz'),
        'purpose' => __("This cookie is set by iThemes Security Plugin to change the backend login URL for additional security.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is set by iThemes Security Plugin to change the backend login URL for additional security.", 'complianz'),
    ),

    'ET_Editor' => array('functional' => true,
        'used_names' => array('et-editor-available-post'),
        'unique_used_names' => array('et-editor-available-post'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("ET Editor", 'complianz'),
        'purpose' => __("This cookie is set by ET Editor and is being used as a session cookie.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is set by ET Editor and is being used as a session cookie.", 'complianz'),
    ),

    'Yith_WooCommerce' => array('functional' => true,
        'used_names' => array('yith_wcwl_products'),
        'unique_used_names' => array('yith_wcwl_products'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Yith", 'complianz'),
        'purpose' => __("This cookie is set by Yith WooCommerce and makes it possible for visitors to make their own wishlist.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is set by Yith WooCommerce and makes it possible for visitors to make their own wishlist.", 'complianz'),
    ),

    'SlideCheck' => array('functional' => true,
        'used_names' => array('wpgb_visit_last-partial_', 'wpgb_visit_last_php-partial_'),
        'unique_used_names' => array('wpgb_visit_last-partial_', 'wpgb_visit_last_php-partial_'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("SlideCheck", 'complianz'),
        'purpose' => __("This cookie is set to be able to deliver slide shows in headers and other images.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is set to be able to deliver slide shows in headers and other images.", 'complianz'),
    ),

    'Go_Daddy' => array('functional' => true,
        'used_names' => array('_tccl_visitor', '_tccl_visit'),
        'unique_used_names' => array('_tccl_visitor', '_tccl_visit'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Go Daddy", 'complianz'),
        'purpose' => __("This cookie is a persistent Web Hosting Provider (GoDaddy) cookie to monitor website usage performance.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is a persistent Web Hosting Provider (GoDaddy) cookie to monitor website usage performance.", 'complianz'),
    ),

    'SPU_Closing' => array('functional' => true,
        'used_names' => array('spu_closing', 'spu_closing-partial_'),
        'unique_used_names' => array('spu_closing', 'spu_closing-partial_'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("SPU Closing", 'complianz'),
        'purpose' => __("This cookie is used to determine whether someone closes the web browser.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to determine whether someone closes the web browser.", 'complianz'),
    ),

    'Smartlook' => array('analytical' => true,
        'used_names' => array('SL_C_xxxxxx_SID', 'SL_C_xxxxxx_KEY', 'SL_C_xxxxxx_SID', 'SL_C_xxxxxx_VID', 'AWSELB'),
        'unique_used_names' => array('SL_C_partial_SID', 'SL_C_partial_KEY', 'SL_C_partial_SID', 'SL_C_partial_VID', 'AWSELB'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Smartlook", 'complianz'),
        'purpose' => __("This cookie is used as a service to track visitor behavior on the website.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used as a service to track visitor behavior on the website.", 'complianz'),
    ),

    'BST_Systemtechnik' => array('functional' => true,
        'used_names' => array('bst_accepted'),
        'unique_used_names' => array('bst_accepted'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("BST Systemtechnik", 'complianz'),
        'purpose' => __("This cookie is used to place a cookie banner.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to place a cookie banner.", 'complianz'),
    ),

    'SmartSupp' => array('marketing' => true,
        'used_names' => array('ssupp.visits', 'ssupp.chatid', 'ssupp_vid', 'ssupp_visits', 'ssupp_chatid'),
        'unique_used_names' => array('ssupp.visits', 'ssupp.chatid', 'ssupp_vid', 'ssupp_visits', 'ssupp_chatid'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("SmartSupp", 'complianz'),
        'purpose' => __("This cookie is used to use our Livechat functions which is able to assist you during your visit.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to use our Livechat functions which is able to assist you during your visit.", 'complianz'),
    ),

    'Redux' => array('analytical' => true,
        'used_names' => array('redux_current_tab'),
        'unique_used_names' => array('redux_current_tab'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Redux", 'complianz'),
        'purpose' => __("Cookie to improve the user movement in the site. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Cookie to improve the user movement in the site.", 'complianz'),
    ),
    'WP_Globus' => array('functional' => true,
        'used_names' => array('wpglobus-language-old', 'wpglobus-language'),
        'unique_used_names' => array('wpglobus-language-old', 'wpglobus-language'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("WP Globus", 'complianz'),
        'purpose' => __("This is a cookie which makes it able to view multiple languages on the website. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This is a cookie which makes it able to view multiple languages on the website.", 'complianz'),
    ),
    'Paid_Membership_Pro' => array('functional' => true,
        'used_names' => array('pmpro_visit'),
        'unique_used_names' => array('pmpro_visit'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Paid Membership Pro", 'complianz'),
        'purpose' => __("This is a cookie makes it able to subscribe to certain services with recurring payments. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This is a cookie makes it able to subscribe to certain services with recurring payments.", 'complianz'),
    ),
    'Active_Campaign' => array('marketing' => true,
        'used_names' => array('ac_enable_tracking'),
        'unique_used_names' => array('ac_enable_tracking'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("Active Campaign", 'complianz'),
        'purpose' => __("This is a cookie makes it able to subscribe to certain services with recurring payments. ", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("ActiveCampaign stores the data collected on its servers which is used to personalize our communication, improve interaction, provide statistics on website usage, and improve our products, services and offers.", 'complianz'),
    ),
    'LiteSpeed' => array('functional' => true,
        'used_names' => array('_lscache_vary'),
        'unique_used_names' => array('_lscache_vary'),
        'privacy_policy_url' => '[privacy_policy_url]',
        'label' => __("LiteSpeed", 'complianz'),
        'purpose' => __("This is a cookie that stores users' login status and what the role of the current user is.", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This is a cookie that stores users' login status and what the role of the current user is.", 'complianz'),
    ),
);
