<?php
defined('ABSPATH') or die("you do not have acces to this page!");
/*
 * Unique used names must be unique for this service. It is used to link the service to the cookie.
 * used names should contain all used cookie names
 * if match should be made on partial of cookiename only, prefix with "partial_"
 *
 * */
$this->ignore_cookie_list = array('wp-settings', 'redux_blast', 'wordpress_test_cookie');

$this->known_cookie_keys = array(
    'wordPress_metrics' => array('functional' => true,
        'used_names' => array('tk_lr','tk_or' ),
        'unique_used_names' => array('tk_lr','tk_or'),
        'privacy_policy_url' => 'https://wordpress.org/about/privacy/',
        'label' => "WordPress.com",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("Collection of internal metrics for user activity, used to improve user experience.", 'complianz'),
    ),

    'wordpress' => array(
        'functional' => true,
        'used_names' => array('_wordpress_'),
        'unique_used_names' => array('partial_wordpress_'),
        'label' => "WordPress",
        'privacy_policy_url' => 'https://wordpress.org',
        'purpose' => __("WordPress log in cookie", 'complianz'),
        'storage_duration' => __("30 days", 'complianz'),
        'description' => __("Cookie to keep you logged in", 'complianz'),
    ),
    'googlemaps' => array(
        'functional' => true,
        'used_names' => array(),
        'unique_used_names' => array(),
        'label' => "Google Maps",
        'privacy_policy_url' => 'https://maps.google.com',
        'purpose' => __("Google Maps cookie", 'complianz'),
        'storage_duration' => __("30 days", 'complianz'),
        'description' => __("Google Maps cookies to track individual users.", 'complianz'),
    ),

    'youtube' => array(
        'functional' => true,
        'used_names' => array(''),
        'unique_used_names' => array(''),
        'label' => "YouTube",
        'privacy_policy_url' => 'https://youtube.com',
        'purpose' => __("Youtube cookie to track individual users", 'complianz'),
        'storage_duration' => __("30 days", 'complianz'),
        'description' => __("Cookies to track individual users.", 'complianz'),
    ),

    'google-analytics' => array(
        'functional' => true,
        'used_names' => array('_ga', '_gid', '_gat'),
        'unique_used_names' => array('partial_gat_UA', '_ga', '_gid', '_gat', 'partial_utm', '__utmb', '__utmc', 'UTMD__', '__utmv', '__utmz'),
        'privacy_policy_url' => 'https://analytics.google.com',
        'label' => "Google Analytics",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'mixpanel' => array(
        'functional' => true,
        'used_names' => array('mixpanel'),
        'unique_used_names' => array('partial_mixpanel'),
        'privacy_policy_url' => '',
        'label' => __("Mixpanel", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'matomo' => array(
        'functional' => true,
        'used_names' => array('_pk_ref', '_pk_cvar', '_pk_id', '_pk_ses', '_pk_hsr', 'piwik_ignore'),
        'unique_used_names' => array('partial__pk_', 'partial_piwik'),
        'privacy_policy_url' => 'https://matomo.com',
        'label' => "Matomo",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'php-session' => array('functional' => true,
        'used_names' => array('PHPSESSID'),
        'unique_used_names' => array('PHPSESSID'),
        'privacy_policy_url' => '',
        'label' => "PHP Session ID",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'stripe' => array('functional' => true,
        'used_names' => array('__stripe_mid', '__stripe_sid'),
        'unique_used_names' => array('__stripe_mid', 'partial__stripe_'),
        'privacy_policy_url' => 'https://stripe.com',
        'label' => __("Stripe payment gateway", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'complianz' => array('functional' => true,
        'used_names' => array('cmplz_id', 'complianz_consent_status', 'complianz_policy_id'),
        'unique_used_names' => array('cmplz_id', 'cookieconsent_status', 'complianz_consent_status', 'complianz_policy_id'),
        'privacy_policy_url' => 'https://complianz.io',
        'label' => "Complianz",
        'purpose' => __("Remember the cookie warning choice", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'add-this' => array('functional' => false,
        'used_names' => array('__atuvs', '__atuvc', 'psc', 'uid', 'uit', 'uvc', 'cw_id', 'loc', 'mus', 'na_id', 'na_tc', 'uvc', 'uid', 'ouid'),
        'unique_used_names' => array('__atuvs', '__atuvc', 'cw_id', 'na_id'),
        'privacy_policy_url' => 'https://addthis.com',
        'label' => "Add This",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'CloudFlare' => array('functional' => false,
        'used_names' => array('__cfduid'),
        'unique_used_names' => array('__cfduid'),
        'privacy_policy_url' => 'https://www.cloudflare.com/privacypolicy/',
        'label' => "CloudFlare",
        'purpose' => __("CloudFlare", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("The __cfduid cookie is used to identify individual clients behind a shared IP address and apply security settings on a per-client basis. ", 'complianz'),
    ),
    'adyen' => array('functional' => false,
        'used_names' => array('hppsession'),
        'unique_used_names' => array('hppsession'),
        'privacy_policy_url' => 'https://adyen.com',
        'label' => "Adyen",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'facebook' => array('functional' => false,
        'used_names' => array('fbm_', 'actppresence', 'sb', 'csm', 'c_user', 'frstxs', 'datr'),
        'unique_used_names' => array('partial_fbm_', 'actppresence', 'sb', 'csm', 'c_user', 'frstxs', 'datr'),
        'privacy_policy_url' => 'https://facebook.com',
        'label' => "Facebook",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'criteo' => array('functional' => false,
        'used_names' => array('hid', 'has_js', 'tk', 'uic', 'ect', 'udc', 'dis', 'udi'),
        'unique_used_names' => array('hid', 'has_js', 'tk', 'uic', 'ect', 'udc', 'dis', 'udi'),
        'privacy_policy_url' => 'https://criteo.com',
        'label' => "Criteo",
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'google-ads-optimization' => array('functional' => false,
        'used_names' => array('PREF', 'NID', 'id', '_drt_'),
        'unique_used_names' => array('PREF', 'NID', '_drt_'),
        'privacy_policy_url' => '',
        'label' => __("Google Ads Optimization", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'cloudflare' => array('functional' => false,
        'used_names' => array('__cfduid'),
        'unique_used_names' => array('__cfduid'),
        'privacy_policy_url' => '',
        'label' => __("Cloudflare", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'salesforce-liveagent' => array('functional' => false,
        'used_names' => array('liveagent_oref', 'liveagent_sid', 'liveagent_vc', 'liveagent_ptid'),
        'unique_used_names' => array('partial_liveagent_'),
        'privacy_policy_url' => 'https://www.salesforce.com/company/privacy/',
        'label' => "Salesforce Liveagent",
        'purpose' => __("Real-time chat cookie", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("This cookie is used to chat real-time with employees.", 'complianz'),
    ),

    'livechat' => array('functional' => false,
        'used_names' => array('__lc.visitor_id', 'hide_eye_catcher', 'autoinvite_callback', '__lc.visitor_id', 'lc_invitation_opened', 'lc_window_state', 'lc_sso9818825', '__lc_visitor_id'),
        'unique_used_names' => array('wpfront-notification-bar-landingpage', 'partial__lc.visitor_id', 'partial_lc_'),
        'privacy_policy_url' => 'https://www.livechat.com/privacy/',
        'label' => "Livechat",
        'purpose' => __("Real-time chat cookie", 'complianz'),
        'storage_duration' => __("365 days", 'complianz'),
        'description' => __("Live Chat is a chat system which can help users with questions regarding our products and website.", 'complianz'),
    ),

    'doublecLick' => array('functional' => false,
        'used_names' => array('idIDE', 'test_cookie', 'id', '___gads', '_drt_', 'DSID', 'IDE'),
        'unique_used_names' => array('idIDE', 'DSID'),
        'privacy_policy_url' => '',
        'label' => __("DoubleCLick", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'optimizely' => array('functional' => false,
        'used_names' => array('end_user_id', 'cdnoptimizely', 'ab_optimizely'),
        'unique_used_names' => array('cdnoptimizely', 'ab_optimizely'),
        'privacy_policy_url' => '',
        'label' => __("Optimizely", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'google-adwords' => array('functional' => false,
        'used_names' => array('NID', 'HSID', 'SSIDAPISID', 'SAPISID', '__ut'),
        'unique_used_names' => array('NID', 'HSID', 'SSIDAPISID', 'SAPISID'),
        'privacy_policy_url' => '',
        'label' => __("Google Adwords", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'hotjar' => array('functional' => false,
        'used_names' => array('_hjUserId', '_hjIncludedInSample', '_hjMinimizedTestersWidgets', '_hjClosedSurveyInvites', '_hjDonePolls', '_hjMinimizedPolls', '_hjDoneTestersWidgets'),
        'unique_used_names' => array('_hjUserId', '_hjIncludedInSample', '_hjMinimizedTestersWidgets', '_hjClosedSurveyInvites', '_hjDonePolls', '_hjMinimizedPolls', '_hjDoneTestersWidgets'),
        'privacy_policy_url' => '',
        'label' => __("Hotjar", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'visual-website-optimizer' => array('functional' => false,
        'used_names' => array('_vis_opt_out', '_vis_opt_s', 'partial_vis_opt_exp', '_vis_opt_test_cookie', '_vis_opt_exp_[experiment_id]_goal_[goal_id]', 'partial_vwo_', '_vwo_uuid_v2'),
        'unique_used_names' => array('_vwo_uuid_v2'),
        'privacy_policy_url' => '',
        'label' => __("Visual Website Optimizer", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'snoobi' => array('functional' => false,
        'used_names' => array('Snoobisession_adcalls_nl', 'SnoobiID', 'Snoop_testi'),
        'unique_used_names' => array('Snoobisession_adcalls_nl', 'SnoobiID', 'Snoop_testi'),
        'privacy_policy_url' => '',
        'label' => __("Snoobi", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'Adcalls' => array('functional' => false,
        'used_names' => array('acalltracker', 'acalltrackersession'),
        'unique_used_names' => array('acalltracker', 'acalltrackersession'),
        'privacy_policy_url' => '',
        'label' => __("Adcalls", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'call-tracking-metrics' => array('functional' => false,
        'used_names' => array('ctm'),
        'unique_used_names' => array('ctm'),
        'privacy_policy_url' => '',
        'label' => __("Call Tracking Metrics", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'tealium' => array('functional' => false,
        'used_names' => array('utag_main'),
        'unique_used_names' => array('utag_main'),
        'privacy_policy_url' => '',
        'label' => __("Tealium", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'Adkernel' => array('functional' => false,
        'used_names' => array('ADK_EX_15', 'ADKUID'),
        'unique_used_names' => array('ADK_EX_15', 'ADKUID'),
        'privacy_policy_url' => '',
        'label' => __("Adkernel", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'gigya-com' => array('functional' => false,
        'used_names' => array('gig_hasGmid'),
        'unique_used_names' => array('gig_hasGmid'),
        'privacy_policy_url' => '',
        'label' => __("Gigya.com", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'casalemedia-com' => array('functional' => false,
        'used_names' => array('CMDD', 'CMRUM3', 'CMSC'),
        'unique_used_names' => array('CMDD', 'CMRUM3', 'CMSC'),
        'privacy_policy_url' => '',
        'label' => __("casalemedia.com", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'demdex-net' => array('functional' => false,
        'used_names' => array('dextp'),
        'unique_used_names' => array('dextp'),
        'privacy_policy_url' => '',
        'label' => __("demdex.net", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'everesttech-net' => array(
      'functional' => false,
        'used_names' => array('everest_g_v2', 'everest_session_v2', 'ev_sync_dd'),
        'unique_used_names' => array('everest_g_v2', 'everest_session_v2', 'ev_sync_dd'),
        'privacy_policy_url' => '',
        'label' => __("everesttech.net", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'mathtag-com' => array('functional' => false,
        'used_names' => array('uuid', 'uuidc', 'HRL8'),
        'unique_used_names' => array('HRL8'),
        'privacy_policy_url' => '',
        'label' => __("mathtag.com", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'zopim' => array('functional' => false,
        'used_names' => array('__zlcmid', '__zprivacy'),
        'unique_used_names' => array('__zlcmid', '__zprivacy', '__zlcprivacy'),
        'privacy_policy_url' => '',
        'label' => __("Zopim", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'linkedin' => array('functional' => false,
        'used_names' => array('X-LI-IDC'),
        'unique_used_names' => array('X-LI-IDC'),
        'privacy_policy_url' => '',
        'label' => __("Linkedin", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'twitter' => array('functional' => false,
        'used_names' => array('metrics_token'),
        'unique_used_names' => array('metrics_token'),
        'privacy_policy_url' => '',
        'label' => __("Twitter", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'googleplus' => array(
        'functional' => false,
        'used_names' => array(),
        'unique_used_names' => array(),
        'privacy_policy_url' => 'https://google.com/privacy',
        'label' => __("Google Plus", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'sharethis' => array('functional' => false,
        'used_names' => array('__stid', 'uset', '_utmb', '_utmz', '_utmc', '_utma', 'optimizelyPendingLogEvents', 'optimizelyBuckets', 'optimizelySegments', 'optimizelyEndUserId', '__uset', 'stdlxmap', '_stacxiommap', '_stamap', '_stgmap', '_stid', 'UID', 'UIDR'),
        'unique_used_names' => array('__sharethis_cookie_test__'),
        'privacy_policy_url' => '',
        'label' => __("Share this", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),


    'jetpack' => array('functional' => false,
        'used_names' => array('tk_tc', 'tk_qs', 'tk_ai'),
        'unique_used_names' => array('tk_tc', 'tk_qs', 'tk_ai'),
        'privacy_policy_url' => '',
        'label' => __("JetPack", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'newrelic' => array('functional' => false,
        'used_names' => array('NRMLID', 'NRMPID', 'NRREFL', 'NRREFP', 'optimizelyEndUserId', 'optimizelySegments', 'optimizelyBuckets', '__qca', '__ar_v4', '_biz_uid', '_biz_sid', '_biz_nA', '_biz_pendingA', '_ceg.s', '_ceg.u', 'ajs_user_id', 'ajs_group_id', 'ajs_anonymous_id', '__distillery', '_mkto_trk', 'ei_client_id', 'wcsid', 'hblid', '_oklv', '_okdetect', 'olfsk', '_okbk', '_ok', 'optimizelyPendingLogEvents', '_gal'),
        'unique_used_names' => array('NRMLID', 'NRMPID', 'NRREFL', 'NRREFP'),
        'privacy_policy_url' => '',
        'label' => __("Newrelic", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

    'google' => array(
        'functional' => false,
        'used_names' => array('OGPC', 'SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'CONSENT', 'SNID', 'NID'),
        'unique_used_names' => array('OGPC', 'SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'SNID', 'NID'),
        'privacy_policy_url' => '',
        'label' => __("Google", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'slimstat' => array('functional' => false,
        'used_names' => array('slimstat_tracking_code'),
        'unique_used_names' => array('slimstat_tracking_code'),
        'privacy_policy_url' => '',
        'label' => __("Slimstat Tracking Code", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),
    'wpdiscuz_last_visit' => array('functional' => false,
        'used_names' => array('wpdiscuz_last_visit'),
        'unique_used_names' => array('wpdiscuz_last_visit'),
        'privacy_policy_url' => '',
        'label' => __("WP Discuz", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("", 'complianz'),
    ),

      'wpml' => array('functional' => true,
        'used_names' => array('wpml_browser_redirect_test', '_icl_current_language', '_icl_visitor_lang_js', '_icl_current_admin_language_', ),
        'unique_used_names' => array('partial_wpml', 'partial__icl_', '_icl_visitor_lang_js'),
        'privacy_policy_url' => 'https://wpml.org/documentation/privacy-policy-and-gdpr-compliance/',
        'label' => __("WPML", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("WPML is a cookie used to provide different languages for an user. Also it checks which language a user is using.", 'complianz'),
    ),


    'Heap' => array('analytical' => true,
        'used_names' => array('_hp2_ses' ),
        'unique_used_names' => array('partial_hp2'),
        'privacy_policy_url' => 'https://heapanalytics.com/privacy',
        'label' => __("Heap Analytics", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("The Heap cookie captures every user interaction from web, mobile, and cloud services.", 'complianz'),
    ),

    'wordfence_human' => array('functional' => true,
        'used_names' => array('wordfence_verifiedHuman' ),
        'unique_used_names' => array('wordfence_verifiedHuman'),
        'privacy_policy_url' => 'https://www.wordfence.com/privacy-policy/',
        'label' => __("WordFence", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("Cookie used to verify if the visitor is a bot or human.", 'complianz'),
    ),

    'wordfence' => array('tracking' => true,
        'used_names' => array('wfvt_3883187383' ),
        'unique_used_names' => array('partial_wfvt_'),
        'privacy_policy_url' => 'https://www.wordfence.com/privacy-policy/',
        'label' => __("WordFence", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("Tracks a user duration so that so that the page views can be grouped together.", 'complianz'),
    ),

    'MouseFlow' => array('analytical' => true,
        'used_names' => array('partial_mf' ),
        'unique_used_names' => array('partial_mf'),
        'privacy_policy_url' => 'https://mouseflow.com/privacy/',
        'label' => __("MouseFlow", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("A cookie for checking if the user is new or returning.", 'complianz'),
    ),

    'Sumo' => array('analytical' => true,
        'used_names' => array('__smVID', '__smToken', 'partial_smSessionId', '__smScrollBoxShown', '__smListBuilderShown' ),
        'unique_used_names' => array('__smVID', '__smToken', 'partial_smSessionId', '__smScrollBoxShown', '__smListBuilderShown'),
        'privacy_policy_url' => 'https://help.sumo.com/hc/en-us/articles/218958727-Privacy-Policy',
        'label' => __("Sumo", 'complianz'),
        'purpose' => __("", 'complianz'),
        'storage_duration' => __("", 'complianz'),
        'description' => __("Sumo uses cookies to control many different things in users browsers. These cookies control everything from determining if a visitor is opted-out of a certain popup to telling Sumo whether or not to display a Bar. ", 'complianz'),
    ),

);
